### ISSUE TITLE
Missing boost file?

### ISSUE THREAD

**Issue by jthiels** [IBAMR/autoibamr#68]
Hi,
When using the script, I got this error while compiling IBAMR:
/scratch/support_root/support/jthiels/ibamr/tmp/unpack/IBAMR-0.10.1/ibtk/contrib/boost/boost/type_traits/detail/has_binary_operator.hpp:98:57: fatal error: boost/type_traits/detail/is_likely_lambda.hpp: No such file or directory
 #include <boost/type_traits/detail/is_likely_lambda.hpp>

I had run ./autoibamr.sh -j16 -y --enable-native-optimizations -p "/scratch/support_root/support/jthiels/ibamr"  on a centos7 cluster; I tried changing autoibamr.cfg to use v0.10.0 instead of v0.10.1 but got the same error.

**Comment by drwells** [comment]
That's probably related to https://github.com/IBAMR/IBAMR/pull/1425. Unfortunately, that patch came in after 0.10 came out so it won't be a part of a release until this summer. I suspect the problem here is that boost detects an older version of GCC and tries to include C++11 shims that we don't need (and I didn't add into the bundled directory of IBAMR until recently since that configuration is under-tested).

Are you using gcc 4.8? One fix would be to use a newer C++ compiler.

**Comment by boyceg** [comment]
@drwells, is it worth doing one more patch release for 0.10 if this impacts usability on older compilers that are nominally supported?

**Comment by boyceg** [comment]
Also, is there documentation on how to point autoibamr to use IBAMR `master`?

**Comment by drwells** [comment]
1. I thought that we updated boost more than one release ago, but my recollection was wrong - that update was in September of last year. Hence this issue is tied to this particular release. and we really should fix it. I won't have time to do that this week, though.
2. autoibamr doesn't yet support working off master. Some of the code to switch branches is present (we inherited it from candi) but other parts (like juggling IBAMR patches) are not yet implemented.

**Comment by jthiels** [comment]
Hi,

I was able to get it to work by loading gcc 8.2.0.  I had gone down to gcc
4.2.0 as there had been issues with compiling it manually with competing
gfortran.so version warnings in PETSC and IBAMR as well as MPI issues that
I couldn't self-diagnose.

Thank you very much for your help.

Best,
John

**Comment by drwells** [comment]
Glad to hear it.

There are some other unresolved boost bugs that only appear with older versions of GCC - see also https://github.com/IBAMR/IBAMR/pull/1439 (and in particular https://github.com/IBAMR/IBAMR/pull/1439/commits/8b520bc9e7dcc4e36a8075664ef4e43185ca9396)
